name: Bug report
description: Report a reproducible problem
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is happening?
      placeholder: Clear and concise bug description
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Exact steps, commands, and inputs
      placeholder: |
        1. Run command...
        2. Observe...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      placeholder: e.g. 0.3.0
  - type: textarea
    id: env
    attributes:
      label: Environment
      placeholder: OS, Node version, shell, CI/local
  - type: textarea
    id: logs
    attributes:
      label: Logs and screenshots
      description: Paste relevant logs. Remove secrets.
